version: '3.8'

services:
  frontend:
    build: ./survey-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./survey-app:/app
      - /app/node_modules
      - /app/.next

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://frontend:3000
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=surveydb
      - POSTGRES_USER=surveyuser
      - POSTGRES_PASSWORD=surveypass

volumes:
  postgres_data: 