version: '3.8'

services:
  frontend:
    image: limjiawei/survey-app-frontend
    build: ./survey-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development
      - NEXTAUTH_SECRET=esKauTs3L1nd38nH0ruC7tA9jpKnsoqeEXhCsJkRE0w=
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - ./survey-app:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  backend:
    image: limjiawei/survey-app-backend
    build: ./backend
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py seed_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend,152.42.209.31
      - CORS_ALLOWED_ORIGINS=http://152.42.209.31:3000
      - POSTGRES_DB=surveydb
      - POSTGRES_USER=surveyuser
      - POSTGRES_PASSWORD=password
      - DATABASE_URL=postgres://surveyuser:password@db:5432/surveydb
    volumes:
      - ./backend:/app
      - media_volume:/app/media
      - static_volume:/app/static
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=surveydb
      - POSTGRES_USER=surveyuser
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
  media_volume:
  static_volume: 